import { ipcMain, dialog, shell, BrowserWindow } from 'electron'
import { mkdir, readFile } from 'node:fs/promises'
import { backupsDir } from '../lib/paths'
import { withDataLock, writeCollection, writeDecks, writeWishlist } from '../lib/dataFiles'
import { readBundle, snapshot } from '../lib/backups'
import { writeJsonAtomic } from '../lib/jsonStore'
import { parseBackupBundle } from '../lib/backupBundle'

export interface ImportResult {
  imported: boolean
  deckCount: number
  wishlistCount: number
  collectionCount: number
  /** Entries in the file that didn't look like decks/wishlist rows and were left out. */
  skipped: number
  error?: string
}

function emptyResult(extra: Partial<ImportResult> = {}): ImportResult {
  return { imported: false, deckCount: 0, wishlistCount: 0, collectionCount: 0, skipped: 0, ...extra }
}

// Backups cover decks, wishlist and collection — the card cache and formats
// cache are just downloaded API data (regenerated by "Sync card data"), and
// pawmodoro-sync.json holds a live Supabase login token that has no business
// leaving this machine, let alone landing in a git repo.
export function registerBackupIpc(): void {
  ipcMain.handle('backup:export', async (e): Promise<boolean> => {
    const win = BrowserWindow.fromWebContents(e.sender)
    const bundle = await readBundle()

    const options: Electron.SaveDialogOptions = {
      defaultPath: `deckbuilder-backup-${new Date().toISOString().slice(0, 10)}.json`,
      filters: [{ name: 'JSON', extensions: ['json'] }],
    }
    const result = win ? await dialog.showSaveDialog(win, options) : await dialog.showSaveDialog(options)
    if (result.canceled || !result.filePath) return false
    await writeJsonAtomic(result.filePath, bundle)
    return true
  })

  ipcMain.handle('backup:openFolder', async (): Promise<void> => {
    await mkdir(backupsDir(), { recursive: true })
    await shell.openPath(backupsDir())
  })

  ipcMain.handle('backup:import', async (e): Promise<ImportResult> => {
    const win = BrowserWindow.fromWebContents(e.sender)
    await mkdir(backupsDir(), { recursive: true })
    // Opens in the automatic-backups folder, so restoring a snapshot is two clicks.
    const options: Electron.OpenDialogOptions = {
      defaultPath: backupsDir(),
      properties: ['openFile'],
      filters: [{ name: 'JSON', extensions: ['json'] }],
    }
    const result = win ? await dialog.showOpenDialog(win, options) : await dialog.showOpenDialog(options)
    if (result.canceled || result.filePaths.length === 0) return emptyResult()

    let bundle: unknown
    try {
      bundle = JSON.parse(await readFile(result.filePaths[0], 'utf-8'))
    } catch (err) {
      return emptyResult({ error: `Couldn't read that file as JSON (${err instanceof Error ? err.message : String(err)}).` })
    }
    const parsed = parseBackupBundle(bundle)
    if (!parsed.ok) return emptyResult({ error: parsed.error })
    const { decks, wishlist, collection, skipped } = parsed

    await withDataLock(async () => {
      // Keep what's about to be overwritten so a wrong restore can be reversed.
      await snapshot('pre-restore')
      if (decks) await writeDecks(decks)
      if (wishlist) await writeWishlist(wishlist)
      if (collection) await writeCollection(collection)
    })

    return {
      imported: true,
      deckCount: decks?.length ?? 0,
      wishlistCount: wishlist?.length ?? 0,
      collectionCount: collection ? Object.keys(collection).length : 0,
      skipped,
    }
  })
}
