import { ipcMain, dialog, BrowserWindow } from 'electron'
import { readFile, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { decksFile, wishlistFile } from '../lib/paths'

async function readJsonArrayIfExists(path: string): Promise<unknown[]> {
  if (!existsSync(path)) return []
  try {
    const parsed = JSON.parse(await readFile(path, 'utf-8'))
    return Array.isArray(parsed) ? parsed : []
  } catch {
    return []
  }
}

// Only decks and the wishlist get backed up — the card cache and formats
// cache are just downloaded API data (regenerated by "Sync card data"),
// and pawmodoro-sync.json holds a live Supabase login token that has no
// business leaving this machine, let alone landing in a git repo.
export function registerBackupIpc(): void {
  ipcMain.handle('backup:export', async (e): Promise<boolean> => {
    const win = BrowserWindow.fromWebContents(e.sender)
    const decks = await readJsonArrayIfExists(decksFile())
    const wishlist = await readJsonArrayIfExists(wishlistFile())
    const bundle = { version: 1, exportedAt: new Date().toISOString(), decks, wishlist }

    const options: Electron.SaveDialogOptions = {
      defaultPath: `deckbuilder-backup-${new Date().toISOString().slice(0, 10)}.json`,
      filters: [{ name: 'JSON', extensions: ['json'] }],
    }
    const result = win ? await dialog.showSaveDialog(win, options) : await dialog.showSaveDialog(options)
    if (result.canceled || !result.filePath) return false
    await writeFile(result.filePath, JSON.stringify(bundle, null, 2), 'utf-8')
    return true
  })

  ipcMain.handle(
    'backup:import',
    async (e): Promise<{ imported: boolean; deckCount: number; wishlistCount: number; error?: string }> => {
      const win = BrowserWindow.fromWebContents(e.sender)
      const options: Electron.OpenDialogOptions = { properties: ['openFile'], filters: [{ name: 'JSON', extensions: ['json'] }] }
      const result = win ? await dialog.showOpenDialog(win, options) : await dialog.showOpenDialog(options)
      if (result.canceled || result.filePaths.length === 0) return { imported: false, deckCount: 0, wishlistCount: 0 }

      let bundle: unknown
      try {
        const raw = await readFile(result.filePaths[0], 'utf-8')
        bundle = JSON.parse(raw)
      } catch (err) {
        return {
          imported: false,
          deckCount: 0,
          wishlistCount: 0,
          error: `Couldn't read that file as JSON (${err instanceof Error ? err.message : String(err)}).`,
        }
      }
      if (typeof bundle !== 'object' || bundle === null) {
        return { imported: false, deckCount: 0, wishlistCount: 0, error: "That file isn't a backup bundle." }
      }

      const { decks: rawDecks, wishlist: rawWishlist } = bundle as { decks?: unknown; wishlist?: unknown }
      const decks = Array.isArray(rawDecks) ? rawDecks : []
      const wishlist = Array.isArray(rawWishlist) ? rawWishlist : []

      await writeFile(decksFile(), JSON.stringify(decks, null, 2), 'utf-8')
      await writeFile(wishlistFile(), JSON.stringify(wishlist, null, 2), 'utf-8')
      return { imported: true, deckCount: decks.length, wishlistCount: wishlist.length }
    },
  )
}
